
# services:
#   credit-rating-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"  # Map container port 8080 to host port 8080
#    env_file:
#      - .env  # Load environment variables from the .env file
#    volumes:
#      - .:/app  # Mount the local directory to the container (optional)

#version: '3.8'
#
#services:
#  credit-rating-api:
#    image: '698subhashchandra/credit-rating-api:latest'  # Specify the image to pull from Docker Hub
#    ports:
#      - "8000:8000"  # Map container port 8000 to host port 8000

#version: '3.8'
#
#services:
#  credit-rating-api:
#    image: ${DOCKER_IMAGE:-698subhashchandra/credit-rating-api:v2} # Default fallback if DOCKER_IMAGE is not set
#    ports:
#      - "8000:8000"


#Image Pull form AWS ECR
version: '3'
services:
  app:
    image: docker pull 698subhashchandra/credit-ratingapis:latest
    ports:
      - "8000:8000"  # adjust ports as needed
    restart: unless-stopped
