
# services:
#   credit-rating-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"  # Map container port 8080 to host port 8080
#    env_file:
#      - .env  # Load environment variables from the .env file
#    volumes:
#      - .:/app  # Mount the local directory to the container (optional)

version: '3.8'

services:
  credit-rating-api:
    image: '698subhashchandra/credit-rating-api:latest'  # Specify the image to pull from Docker Hub
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000

